apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s
  region: us-east-2
nodeGroups:
  - name: worker-group
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
