apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-registry
spec:
  selector:
    matchLabels:
      name: container-registry
  template:
    metadata:
      labels:
        name: container-registry
    spec:
      containers:
        - name: app
          image: httpd
          ports:
            - containerPort: 8080
